### ISSUE TITLE
No perms visible in UltraPermission

### ISSUE THREAD

**Issue by TheSoulrester** [Nuytemans-Dieter/BetterSleeping#1]
I am using Ultra Permission https://www.spigotmc.org/resources/ultra-permissions.42678/

But ingame, no perms are visible. maybe, you will contact the author for making BetterSleeping beeing compatible with uPerms?

Here it is explained how to make it compatible: https://github.com/TechsCode/UltraPermissionsDatabase

**Comment by Nuytemans-Dieter** [comment]
Thank you kindly for your suggestion!
I will look into this right now.
