### ISSUE TITLE
Migrate /releases directory to "releases" tab.

### ISSUE THREAD

**Issue by WasabiThumb** [Nuytemans-Dieter/BetterSleeping#112]
The "releases" tab is made for this kind of thing.
https://github.com/Nuytemans-Dieter/BetterSleeping/releases

You can also provide insight on each release with a title and description and even give multiple download links for each release.

**Comment by Nuytemans-Dieter** [comment]
Thank you for notifying me, I had no idea this feature existed. I'll take a look at this soon.

**Comment by Nuytemans-Dieter** [comment]
Future releases will be placed in the releases tab.
