### ISSUE TITLE
Be able to use beds despite permissions

### ISSUE THREAD

**Issue by Airuzen** [Nuytemans-Dieter/BetterSleeping#113]
Sometimes you still want to use beds with or without the bypass permissions, its annoying that the plugin stops you from using beds just because you can type in /bs skip. Its a silly complaint but it would be a nice quality of life feature to be able to still use my beds >_<. You could have players still be able to sleep while still having a message saying "you don't need to use the bed as you have bypass permissions" when they do so, that way their options are open and they are also informed of such.

**Comment by Nuytemans-Dieter** [comment]
Hello, thank you for your suggestion!

I am nearing a stable beta build of v3.0.0 which is a complete rewrite from scratch and a lot more stable. Making this change is a lot easier in the new codebase.
I am interested in this feature, but only to a certain extent (I'm thinking only for bettersleeping.bypass in particular).

I cannot do this for the permission essentials.sleepingignored unfortunately, as Essentials would cause issues and set the time to day instantly whenever all non-OPs sleep.

I will think about this further and schedule this for v3.0.0.

Thanks again!
Dieter

**Comment by Airuzen** [comment]
> Hello, thank you for your suggestion!
> 
> I am nearing a stable beta build of v3.0.0 which is a complete rewrite from scratch and a lot more stable. Making this change is a lot easier in the new codebase.
> I am interested in this feature, but only to a certain extent (I'm thinking only for bettersleeping.bypass in particular).
> 
> I cannot do this for the permission essentials.sleepingignored unfortunately, as Essentials would cause issues and set the time to day instantly whenever all non-OPs sleep.
> 
> I will think about this further and schedule this for v3.0.0.
> 
> Thanks again!
> Dieter

Btw I have found reason for the lack of being able to use beds when having the permissions to use the bypass to be a legitimate issue. The phantom creatures attack you incessantly since you haven't gone to bed AND you still can't use the bed OR the command if another member on the server doesn't have the same bypass permissions.

**Comment by Nuytemans-Dieter** [comment]
> Btw I have found reason for the lack of being able to use beds when having the permissions to use the bypass to be a legitimate issue. The phantom creatures attack you incessantly since you haven't gone to bed AND you still can't use the bed OR the command if another member on the server doesn't have the same bypass permissions.

That's a valid concern. In v3.0.0 players with bypass permissions will be able to sleep but will not be counted towards the required sleeping count.
The beta version is not ready yet, and the beta testers will get 2 weeks to do their testing so I suggest you turn on the disable_phantoms option in the mean time. But consider this fixed :-)

**Comment by Nuytemans-Dieter** [comment]
This has been implemented in a private v3.0.0 build. Closing the issue.
