### ISSUE TITLE
Add the ability to disable certain worlds

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#120]
**Describe the new feature you have in mind**
A config option to disable certain worlds where BetterSleeping will have no effect.

**Comment by Co2Noss** [comment]
Re-adding per world settings with multiverse support has also been suggested.

**Comment by Nuytemans-Dieter** [comment]
> Re-adding per world settings with multiverse support has also been suggested.
> Allow different settings per world. May want to change the topic issue to MutliWorld/Multiverse support

Thank you, changing now.

**Comment by Nuytemans-Dieter** [comment]
Added in da796f6bffe9500fd24b940b80282d4b7c7711f7
