### ISSUE TITLE
Essentials afk ignoring issue

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#139]
**Describe the bug**
Enable afk ignoring in the settings -> Afk players are not ignored! 

**Expected behavior**
Afk players should not be counted

**Comment by Co2Noss** [comment]
Add a timer to check how long a player has been AFK. Hook into EssentialsX.
We can check against getAfkSince() which is probably the epoch time in millis when they went afk

**Comment by Nuytemans-Dieter** [comment]
> Add a timer to check how long a player has been AFK. Hook into EssentialsX.
> We can check against getAfkSince() which is probably the epoch time in millis when they went afk
> 
> https://github.com/EssentialsX/Essentials/search?q=getAfkSince&unscoped_q=getAfkSince

Thank you! You're exactly right.

(for myself:)
Code grabbed from the [Essentials' user class](https://github.com/EssentialsX/Essentials/blob/d9bf099c3d411e5f493180de9c487a93e2fcfda7/Essentials/src/com/earth2me/essentials/User.java).
```
    @Override
    public void setAfk(boolean set, AfkStatusChangeEvent.Cause cause) {
        final AfkStatusChangeEvent afkEvent = new AfkStatusChangeEvent(this, set, cause);
        ess.getServer().getPluginManager().callEvent(afkEvent);
        if (afkEvent.isCancelled()) {
            return;
        }

        this.getBase().setSleepingIgnored(this.isAuthorized("essentials.sleepingignored") || set && ess.getSettings().sleepIgnoresAfkPlayers());
        if (set && !isAfk()) {
            afkPosition = this.getLocation();
            this.afkSince = System.currentTimeMillis();
        } else if (!set && isAfk()) {
            afkPosition = null;
            this.afkMessage = null;
            this.afkSince = 0;
        }
        _setAfk(set);
        updateAfkListName();
    }
```
And:

```
    @Override
    public long getAfkSince() {
        return afkSince;
    }
```

**Comment by Co2Noss** [comment]
Excited to test the webhook and this enhancement!

**Comment by Nuytemans-Dieter** [comment]
Timer has been implemented. Cannot reproduce afk not working though.
