### ISSUE TITLE
Smooth mode does not skip night completely in 1.16.1

### ISSUE THREAD

**Issue by sadimusi** [Nuytemans-Dieter/BetterSleeping#142]
**Describe the bug**
When the sleeping mode is set to `smooth` the player awakens when it is still dark.

**To Reproduce**
1. Join world with default settings
1. Set time to `night` (14000 ticks)
1. Enter a bed
1. Awaken at 20000 ticks

**Expected behavior**
The player should awaken at 24000 ticks.

**Comment by Nuytemans-Dieter** [comment]
Thank you for reporting this issue. I am finishing my exams at the moment but I will investigate this as soon as possible.

**Comment by sadimusi** [comment]
Thanks for the quick reply. I've just played around with the settings a little bit and it appears that with a `base_speedup` of 120 the issue is no longer present and I always awaken at the correct time.

Good luck on you exams!

**Comment by Nuytemans-Dieter** [comment]
That is very good to know, that will help me track down the issue faster.

Thank you!!

**Comment by sadimusi** [comment]
I did some more investigation and it looks like this issue only occurs in very specific circumstances and might actually be a bug in Spigot.

To reproduce it you need to:
1. Set the gamerule `doDaylightCycle` to `false`
2. Be alone on the server (or maybe let everyone sleep at once)

Since everyone is sleeping we get the vanilla sleeping behaviour and are woken up after 100 ticks. If the `base_speedup` has been set high enough this might be enough time for BetterSleeping to skip the night normally. If this isn't the case, then we would expect the vanilla mechanism to skip the night, but spigot actually behaves differently if `doDaylightCycle` is disabled:

```java
TimeSkipEvent event = new TimeSkipEvent(this.getWorld(), NIGHT_SKIP, ...);
if (this.getGameRules().getBoolean(GameRules.DO_DAYLIGHT_CYCLE)) {
    this.getServer().getPluginManager().callEvent(event);
    if (!event.isCancelled()) {
        this.setDayTime(this.getDayTime() + event.getSkipAmount());
    }
}

if (!event.isCancelled()) {
    this.wakeupPlayers();
}
```

So the night is never skipped and we are woken up approximately 100 * `base_speedup` ticks after we went to bed. With the night starting at 13000 ticks and the default `base_speedup` being 60, we can wake up as soon as 19000.

I doubt anyone is using a sleeping plugin with `doDaylightCycle` disabled, so I think you can safely ignore this issue. I'll look a bit further in the difference between Spigot and vanilla behaviour and might open a bug report there.

**Comment by Nuytemans-Dieter** [comment]
Thank you for the research and very extensive explanation!
More people have had problems when setting doDayLightcycle to false. 
I created a new issue for this feature: #152.

I will keep this issue open for just a while, thanks again!

**Comment by Nuytemans-Dieter** [comment]
As a new issue was created for this (which contains a link back here), I can safely close this one.
