### ISSUE TITLE
Setter time mode does not clear weather

### ISSUE THREAD

**Issue by villermen** [Nuytemans-Dieter/BetterSleeping#143]
- BetterSleeping v3.0.1
- SpigotMC 1.6.1 (33ea98fc42b)

I try to keep sleeping mechanics close to vanilla MC, so I switched over to `mode: "setter"` for  the new version. It looks like the time changes when enough people sleep, but the weather does not clear. Is this intended? If so this is a feature request instead of a bug report =)

**Comment by Nuytemans-Dieter** [comment]
Thank you for reporting this issue. The issue may lie somewhere else as a user has reported that essentials' and spigot's weather clearing sometimes don't work either. I will take a look at this soon though.

**Comment by villermen** [comment]
Essentials' `/weather sun` _does_ works on the same server and world and it only calls `World.setStorm(false)`

https://github.com/EssentialsX/Essentials/blob/b7f38517efd7fb0b04a7174e3c1bfa17f88390d1/Essentials/src/com/earth2me/essentials/commands/Commandweather.java#L65

I think the problem is related to 

https://github.com/Nuytemans-Dieter/BetterSleeping/blob/b9190821b0e03782c5fd18ad96797f33943a5245/src/main/java/be/dezijwegel/bettersleeping/timechange/TimeSetter.java#L48-L56

Where if you start with a world time > 0 (still night) it will never be higher than one of the values to make the storm go away.

Anyway I'll get you a PR with a fix eventually.

**Comment by Nuytemans-Dieter** [comment]
That seems to be a very likely cause, thank you for your time and effort!
