### ISSUE TITLE
Variable substitution for `no_permission` message not working for some commands

### ISSUE THREAD

**Issue by sadimusi** [Nuytemans-Dieter/BetterSleeping#145]
**Describe the bug**
The placeholder `<var>` is not replaced when sending the `no_permission` message to a user.

✅ [/bs help](https://github.com/Nuytemans-Dieter/BetterSleeping/blob/c8d3c93e1c82bafa56a3c2cbaa0bc845b1821e60/src/main/java/be/dezijwegel/bettersleeping/commands/bscommands/HelpCommand.java#L30)
:x: [/bs reload](https://github.com/Nuytemans-Dieter/BetterSleeping/blob/c8d3c93e1c82bafa56a3c2cbaa0bc845b1821e60/src/main/java/be/dezijwegel/bettersleeping/commands/bscommands/ReloadCommand.java#L36)
❌ [/bs *](https://github.com/Nuytemans-Dieter/BetterSleeping/blob/c8d3c93e1c82bafa56a3c2cbaa0bc845b1821e60/src/main/java/be/dezijwegel/bettersleeping/commands/CommandHandler.java#L91)

**To Reproduce**
1. Grant no permissions to a player
1. Execute the command `/bs version`

**Expected behavior**
The string `<var>` should be replaced by the current command (e.g. `/bs version`) in the error message.

**Comment by Nuytemans-Dieter** [comment]
Thank you for reporting this issue. I will investigate this soon.

**Comment by Nuytemans-Dieter** [comment]
Fixed in abc027a
