### ISSUE TITLE
RGB Support

### ISSUE THREAD

**Issue by Co2Noss** [Nuytemans-Dieter/BetterSleeping#146]
**Add RGB support for output from en-us.yml, and premium.yml files**
Add new 1.16 RGB support so we can further customize the coloring of output from BetterSleeping3

This is a 1.16 only feature. If you wanted backwards support to continue for versions below this you would need to add a client-side check and find the closest legacy color to the desired RGB combination using a 3D distance check and use that color instead.

**Comment by Nuytemans-Dieter** [comment]
Looked into backwards compatibility, but will not be implemented considering 80+% of servers with BetterSleeping (that share stats) is on version 1.16. Working on rgb support for 1.16+ though.

**Comment by Nuytemans-Dieter** [comment]
Implemented in d22770e for Spigot/Paper and 1.16+ only. For non-supported versions the tags are ignored and removed from each message.
Slight color bug was introduced for the console on Paper only, this issue is ignored
