### ISSUE TITLE
Include a statically named .jar in releases ("BetterSleeping.jar") to make instantiating server from a build file easier.

### ISSUE THREAD

**Issue by Kenajcrap** [Nuytemans-Dieter/BetterSleeping#148]
In a build file like dockerfile it is useful to have static links to the latest release of a plugin. In github releases this is achieved by using the format `https://github.com/Nuytemans-Dieter/BetterSleeping/releases/latest/download/[ASSET_FILE_NAME]`.
So while having a .jar named with its version is useful in most cases, a statically named .jar is necessary in some cases.

Currently I can work around this by using APIs like spiget.org, but it's an easy fix

**Comment by Nuytemans-Dieter** [comment]
That seems like a great idea, consider it planned.

**Comment by Nuytemans-Dieter** [comment]
Future jars will no longer contain the version in their names
