### ISSUE TITLE
Buffs chance enhancement

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#156]
**Describe the new feature you have in mind**

> I suggest buffs/debuffs are given out randomly, such as adding "chances" option to each option.

**Comment by SYNTAG** [comment]
I think the current setup makes sense. It's the tradeoff for not sleeping vs sleeping. Maybe configurations like enabling/disabling that function and the duration of the buff/debuff would make more sense.

**Comment by Nuytemans-Dieter** [comment]
I completely agree. I would implement this along the lines of: 
- Each effect has a chance option. When missing, defaults to 100 (%) so the current behavior does not change
- When giving out effects, check which (de)buffs will be given. Either once for all players or for each player seperately.

Still have to flesh out the details.
