### ISSUE TITLE
Change how the percentage calculation result is rounded

### ISSUE THREAD

**Issue by X12503181** [Nuytemans-Dieter/BetterSleeping#165]
**Describe the bug**

I use the percentage settings for skipping the night on my private server, and I set that to 60%. However when 2 players are online and both of them are in the overworld, only one player sleeping is able to skip the night, despite 2 * 60% = 1.2, which is greater than 1. **This did't happen when I was using 3.0.1; it only happened after switching to 3.0.2 or newer, and switching back to 3.0.1 solved that**.

**To Reproduce**

1. Go to `sleeping_settings.yml`
2. Set the sleeper counter:
```
sleeper_counter: "percentage"
percentage:
  needed: 60
```
3. Reload the plugin and have 2 survival players online in the overworld at the same time.
4. Only one player sleeping is enough to skip the night, and the plugin says only 1 player is needed.

**Expected behavior**

Since 2 * 60% = 1.2, both players are required to sleep to skip the night.

I did not test other settings and other player numbers since it's only a small server used by ~5 people in total, and we often have no more than 2 players online.

**Comment by Nuytemans-Dieter** [comment]
Thank you for the extensive bug report! It means a lot.
I failed to mention this in the patch notes which is my bad. What I did do, is update the description [sleeping_settings.yml](https://github.com/Nuytemans-Dieter/BetterSleeping/blob/v3.0.0/src/main/resources/sleeping_settings.yml) for new users. Existing users (unfortunately) are stuck with the old descriptions.

Some people were confused about rounding up. 11 players in a world with percentage set to 30% would give 3.3, which would mean that 4 players are required while it makes more sense to round to the nearest number (3 in this case). This is why I changed this behavior. Initially, I rounded up to prevent having 0 required players but there is a check for that now.

Do you believe the previous behavior was better? We can definitely discuss this.

**Comment by X12503181** [comment]
Perhaps an option for that? I mean, you can select if you want to round up, or just round to the nearest number.

**Comment by Nuytemans-Dieter** [comment]
I'm a bit torn here as I'd like to clutter configuration as little as possible. But having both options would be nice. I'll ask the beta testers and see what they think.

**Comment by Nuytemans-Dieter** [comment]
I received feedback from two users (below). I'll leave this issue open for now, and am waiting for more opinions.

> i would round to the nearest
> or if you want more work, round it to the nearest .5 decemal
> 2.3 becomes 2, but 2,4 becomes 2,5

> Rounding to the nearest is what would make sense to me

**Comment by Nuytemans-Dieter** [comment]
This issue may be reopened later but won't be implemented for now.
