### ISSUE TITLE
Colors and messages in chat

### ISSUE THREAD

**Issue by LosBagros** [Nuytemans-Dieter/BetterSleeping#179]
Hi please help me to make colorful cool .lang I tried something but it does not work. :)
Thank you Los_Bagros

**Comment by Nuytemans-Dieter** [comment]
Hey! Feel free to share your language file and I'd be happy to correct it for you.

**Comment by LosBagros** [comment]
This is my config file, it work but in consile is something wierd like
https://ctrlv.cz/egN3

# Change to false to stop auto-update-check.
auto_update_check: true

# Set to true before sending a log about an issue.
# Logs trace data required to pinpoint where errors are.
debug: false

# Set the language to use, en_US, nl_NL, lol_US, fr_FR, de_DE, zh_CN, cs-CZ, pt_BR
lang: en_US

# If true this will disable all broadcast messages and allow anyone to sleep.
unrestrictedsleep: false

# Set wake time, Early (23000) or Normal (24000)
waketime: NORMAL

# Delay between sleep, and change to day, in seconds. Minimum 1, recommend 10.
sleepdelay: 5

# Enable(true) or Disable(false) dayskipper
enabledayskipper: false
# Delay between request for DaySkip, and change to night, in seconds. Minimum 1, recommend 10.
dayskipdelay: 10
# If true this will disable ability of players to cancel DaySkipper
unrestricteddayskipper: false
# Require DaySkipper item
dayskipperitemrequired: true

# Set the color of the [CANCEL] link text in broadcast messages. Format RED
# Colors: AQUA, BLACK, GOLD, GRAY, BLUE, GREEN, RED, YELLOW, WHITE
# DARK_AQUA, DARK_BLUE, DARK_GRAY, DARK_GREEN, DARK_RED, DARK_PURPLE, LIGHT_PURPLE
# MAGIC, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
cancelcolor: RED
# Sleep message color, see above
sleepmsgcolor: YELLOW
# Player name color, see above
playernamecolor: WHITE


# Set if cancel is shown or not.
display_cancel: true
# Set to true to broadcast "<player> canceled sleep."
# Set to false not to broadcast that message.
cancelbroadcast: true

# Set the time limit in seconds which a player must wait between attempting to sleep again.
# This prevents a user from spamming chat with sleep messages.
# Set to 0 to disable.
sleeplimit: 0
# Set the time limit in seconds which a player must wait between attempting to cancel again.
# This prevents a user from spamming chat with cancel messages.
# Set to 0 to disable.
cancellimit: 0


# Set whether the player should be told it must be night to use.
notifymustbenight: false

# Set to true to use random sleep msgs.
randomsleepmsgs: true

# Set to the number of sleep msgs
numberofsleepmsgs: 5
# Set msgs for random sleep msgs here "sleepmsg#: <player> msg here"
# Don't forget the space between : and the start of the message.
# sleepmsg1: <player> is sleeping
# sleepmsg2: <player> went to bed. Sweet Dreams
# sleepmsg3: Shhh! <player> is trying to sleep!
# sleepmsg4: <player> is asleep at the wheel
# sleepmsg5: no one<colon> ...\n<player><colon> go to bed.

# Color codes are now usable in sleepmsgs, Example: <BLACK>Black<RESET>Reset
# RGB format is §xFF00FF (§xFFFFFF<player> §x000000i§x999999s §x111111s§x888888l§x222222e§x777777e§x333333p§x666666i§x444444n§x555555g)
# THERE MUST BE A COLOR CODE IN FRONT
sleepmsg1: §xFFFFFF<player> §xFF0000is §xFF7F00s§xFFFF00l§x00FF00ee§x0000FFpi§x4b0082n§x9400D3g
sleepmsg2: §xFFFFFF<player> §x00FFFFwent to bed. Sweet Dreams
sleepmsg3: <YELLOW>Shhh! §xFFFFFF<player> §xFF0000is §xFF00FFtrying §x0000FFto §x00FF00sleep!
sleepmsg4: §xFFFFFF<player> §xFF00FFis asleep at the wheel
sleepmsg5: §xFFFFFFNO ONE<colon> ...\n§xFFFFFF<player><colon> §xFFFF00go to bed.

**Comment by Nuytemans-Dieter** [comment]
Oh woops, I'm afraid you're using a different plugin. BetterSleeping has never had a config file with those options so I'm afraid I can't help you at this time.

**Comment by LosBagros** [comment]
oh sorry

**Comment by Nuytemans-Dieter** [comment]
> oh sorry

Don't worry about it, it's okay.
