### ISSUE TITLE
Can't sleep through a thunder storm

### ISSUE THREAD

**Issue by xenoflot** [Nuytemans-Dieter/BetterSleeping#180]
**Describe the bug**
Sleeping during a thunderstorm has no effect. I just lie there, staring at the ceiling until the sun rises. Too much like RL for me.

**To Reproduce**
Same as per #177 

**Expected behavior**
I expect to be able to sleep the lightning away!

MC 1.16.3
Paper 246
Plugins (27): AdvancedPortals, AntiCheatReloaded, AntiXRay, BetterRTP, BetterSleeping3, BuycraftX, Chunky, CoreProtect, CraftBook, DiscordSRV, dynmap*, Essentials, EssentialsSpawn, FastLeafDecay, Graves, GriefPrevention, ItemSoulBind, LuckPerms, Minepacks, PetMaster, ProtocolLib, ServerRestorer, SilkSpawners, Vault, VeinMiner, WorldEdit, WorldGuard

**Comment by Nuytemans-Dieter** [comment]
Hey! Thank you for reporting a bug. Which version of BetterSleeping are you using? (/bs version if you're not sure)

**Comment by xenoflot** [comment]
v3.0.3. I downloaded it on 18 Oct 2020.  Oh good grief. Your "September" update didn't drop until Oct 19, **the day after** I downloaded! I'll update this tonight and close this ticket tomorrow if all looks well.

**Comment by Nuytemans-Dieter** [comment]
Oh no, that's plain bad luck haha. Hopefully all will be well with the newest version. There should be an update dropping soon though because 3.0.4 throws errors in the console at times (but functions well).

**Comment by xenoflot** [comment]
Yep, that was it. All fixed.
