### ISSUE TITLE
Debuffs for everyone if no one sleeps

### ISSUE THREAD

**Issue by SylveonBottle** [Nuytemans-Dieter/BetterSleeping#181]
Give players the debuff for not sleeping, if nobody in the server slept.

I essentially use this plugin as a "wake up feeling refreshed, because staying up all night is unhealthy" sorta thing by giving really nice buffs for players who sleep and bad debuffs for players who don't.

Players found out they can bypass the debuffs if no one just sleeps (lol..)

I think you can probably check this by checking if any players are in bed a few ticks before daytime (just before players are unable to sleep in beds), and if no one is in bed, just affect @a with the debuffs.

**Comment by Nuytemans-Dieter** [comment]
Thank you for your suggestion.

This is an interesting addition, I like this idea. It's great to hear that someone is using the debuffs as a game mechanic.

I will schedule this for the next update as it should indeed not be too hard to add.
