### ISSUE TITLE
Change of configuration

### ISSUE THREAD

**Issue by WhiteKing21** [Nuytemans-Dieter/BetterSleeping#182]
**Describe the new feature you have in mind**
I have been giving a lot of thought to this matter and to summarize I believe the "optimal" way to approach the core issue that this plugin tackles is this way:
 in the configuration should be 2 options

- A: the minimum percentage of PLAYERS required sleeping to skip the night.
- B: the amount of time that the night would last if A would be sleeping (phrased in the configuration as:  _minimum amount of time that the night should last when players are sleeping_).

obviously B will be always 0 because the night will be skipped if A is met but the quantity is required for the calculations. So it should be actually something like "_the amount of time that the night would last if A would be sleeping but not skipped_"

So any quantity of players lower than B (minimum percentage of players required to skip) will be taken to calculate how quickly will the night speed up. The formula should be similar to this:

(extra)speedup = ((extra)speedup to match up B)*(players asleep/ (A*total players)/100)

I will have some troubles putting examples bc I've been trying to configure the actual ticks in the actual configuration but let me try to.

With these values:
B=80%
A= 7 sec
Players on the server: 10

This will mean that if 8 players are asleep or more, the night will be skipped. But if only 4 players are sleeping the night will SPEEDUP just 50% of what it will speed up if it the night will pass in 7 secs with 8 players (I'm not able to calculate this one but what I am trying to say is that the speedup will be obtained by the relation between A and B)

With these values:
A= 10 sec
B=80%
Players on the server: 20

(80% of 20 is 16) if 16 players or more are sleeping the night will be skipped and if 4 players are sleeping, 

let say that for the night to last 10 secs every second that passes we will have to speedup the night by 100ticks meaning (extra)speedup=100t/s

and 4 players sleeping are just the 25% of the players required to skip, then we will add just 25% of the (extra)speedup this will be exactly 25t/s

It is really hard to explain without knowing the formula to speed up the time so the night will pass in 7 or 10 seconds, but I'm hoping a developer will get my point. 

Although it is hard for a newcomer to configure, This is already an amazing plugin like it is, and it will be great to see this feature implemented.

Thank you!

PS: BTW I'm a java developer and had coded some simple plugins, I will be glad to help

**Comment by Nuytemans-Dieter** [comment]
Hey! Thank you for this very extensive explanation of your idea. It really does mean a lot and would look simpler to configure while maintaining the customisability. However, due to very little spare time I cannot implement it at this time.

This seems like a great way to tacke the core mechanic in BetterSleeping v4 when the development starts. Can't give an ETA just yet, no progress has been made at all (v3 is still doing fine).

Thanks again!

**Comment by Nuytemans-Dieter** [comment]
I can finally say that a variant of this will be implemented in the next update. A completely new design allows us to keep configurability equally detailed but much simpler.

**Comment by Nuytemans-Dieter** [comment]
An adaptation of this idea has been used to simplify (and improve!) BetterSleeping4 configuration on the right branch.
In other words, it will be part of v4!
