### ISSUE TITLE
Disabling message on bypassing.yml doesn't work

### ISSUE THREAD

**Issue by uranderu** [Nuytemans-Dieter/BetterSleeping#206]
**Describe the bug**
Disabling message in bypassing.yml doesn't disable the message.

**To Reproduce**
1. Go to 'bypassing.yml'
2. Change  'send_messages: true' to 'send_messages false:'
3. Do '/bs reload' or restart the server

**Expected behavior**
Disabling the message by setting send_messages to false.

**Comment by Nuytemans-Dieter** [comment]
Hey! Thank you for reporting an issue. This option is only supposed to prevent sending messages to bypassed players, all other players should still receive that message. Could you confirm whether this is the case? 

You can disable a message completely in your lang file under `plugins/bettersleeping3/lang/LANG-CODE.yml` by setting any message to "" and doing `/bs reload`.

**Comment by uranderu** [comment]
Hi!
Yes I'm aware of this. Under the main config.yml I set the language to "silent" to suppress most of the messages.
However my admins still got the bypassed messages so that's why I also changed the setting under bypassing.yml

However now that I am checking silent.yml under the "lang" folder I notice this line: `bypass_message: "&cYou are bypassed so you don't need to sleep, <user>."` You would think that after changing the language to "silent", changing the "send_messages" to false under bypassing.yml and restarting the server plus doing "/bs reload" multiple times this line would be a bit different :P

**Comment by Nuytemans-Dieter** [comment]
Ooh okay, I will investigate this further. I'll schedule this testing (and potentially fixing this) for the next release which is in BETA at this time.

Yeah, I understand the struggle haha. I felt like that would be an important message as that player isn't counted anyway so them sleeping does not have an effect, prevents them from wasting their time. You can still disable it manually if you want though!

**Comment by uranderu** [comment]
I understand your concerns and I think for a lot of people this would be a nice way of handling this. But if you have kind of disabled it two times then it's kind of "Eh?" when you still see messages x)

I disabled it manually now, thanks for your time!

**Comment by Nuytemans-Dieter** [comment]
I completely understand you, I will get a second opinion and I'll see if changes are required in this regard.

No problem at all! Thanks for contacting me.
