### ISSUE TITLE
Add version number

### ISSUE THREAD

**Issue by Drigster** [Nuytemans-Dieter/BetterSleeping#254]
Add version number to downloadable jar name. It's hard to see witch version you use, wihout using console or changing file name

**Comment by Nuytemans-Dieter** [comment]
Hey! Thanks for your suggestion. We used to do this but a suggestion was made, requesting this to change in #148. This allows people to automatically download the latest version and replace their current one. BetterSleeping will auto-notify you when your version is out of date.

**Comment by Drigster** [comment]
Understood, thank you

пт, 30 июл. 2021 г., 16:35 Dieter Nuytemans ***@***.***>:
