### ISSUE TITLE
Spanish Translation for V4

### ISSUE THREAD

**Issue by FunkyNico** [Nuytemans-Dieter/BetterSleeping#255]
Hey there, i translated the plugin for the version 4.

Here is the link: https://hastebin.com/nudetumofu.php
Greetings.

**Comment by Nuytemans-Dieter** [comment]
Hey there, thank you so much!
Am I right in assuming this is Spanish?

**Comment by FunkyNico** [comment]
Yeah. It's spanish. https://paste.ubuntu.com/p/qyxhsx2DTf/ here is new link, because seems that hastebin delete pastes after 1 day.

**Comment by Nuytemans-Dieter** [comment]
> Yeah. It's spanish. https://paste.ubuntu.com/p/qyxhsx2DTf/ here is new link, because seems that hastebin delete pastes after 1 day.

Thank you so much! I do see that you have placed an author comment, which I believe is fair but we are using a bot that makes all config files have the same comments. It wil automatically delete that line, I hope that's not a problem for you. Otherwise, I could give you credits in the readme if you want

**Comment by FunkyNico** [comment]
I have no problem if the line is deleted, but it would be cool to be in the credits also haha.

**Comment by Nuytemans-Dieter** [comment]
> I have no problem if the line is deleted, but it would be cool to be in the credits also haha.

Yeah, of course! Do you prefer the name you credited or your github name?

**Comment by FunkyNico** [comment]
> > I have no problem if the line is deleted, but it would be cool to be in the credits also haha.
> 
> Yeah, of course! Do you prefer the name you credited or your github name?

The name credit it's fine. Greetings.

**Comment by Nuytemans-Dieter** [comment]
Added credits in commit 0684d3ccc8800b7e00241ea2e6951fd7f9f53caa. Cheers!
