### ISSUE TITLE
Error while uploading the plugin to the server

### ISSUE THREAD

**Issue by MatthiasRofl** [Nuytemans-Dieter/BetterSleeping#267]
Guys, help please, I get an error when I upload a plugin to the server
Error occurred while enabling BetterSleeping4 v4.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: javax/inject/Provider

**Comment by Nuytemans-Dieter** [comment]
Hey there, thanks for making an issue! We're working to get that sorted out in the next release! For now, I suggest using the latest version of v3, which will work fine for you. Thank you for your patience and this report!

**Comment by Nuytemans-Dieter** [comment]
@MatthiasRofl should be fixed by now! Cheers!
Dupe of #257
