### ISSUE TITLE
Check bypass permission only when neccessary

### ISSUE THREAD

**Issue by mrjesen** [Nuytemans-Dieter/BetterSleeping#281]
**Describe the new feature you have in mind**
Now I find that the plugin keeps checking for bypass permissions, and to save resources I think I only need to check this permission at night.

**Comment by Nuytemans-Dieter** [comment]
Hey! Thanks for reporting an issue. Which BetterSleeping version are you using?

**Comment by mrjesen** [comment]
sorry duplicated to #265
