### ISSUE TITLE
Plugin Conflict

### ISSUE THREAD

**Issue by iWalk809** [Nuytemans-Dieter/BetterSleeping#288]
Looks like this "CustomTime" Plugin (https://dev.bukkit.org/projects/customtime)
Is conflicting with BetterSleeping. This is a plugin that allows you to speed or slow down time any way you like.
So time was passing faster than normal with this plugin.
the day was set to last 30 minutes and the night 20 minutes with these both commands:
/ct day 30m
/ct night 20m
So is this a bug?
If it's a conflict it means it is a bug too?

**Comment by Nuytemans-Dieter** [comment]
Thank you for reporting this! BetterSleeping now supports configurable day and night lengths out of the box. I think we were able to help you in a ticket on Discord?
