### ISSUE TITLE
Chat message clickable to cancel the server time change

### ISSUE THREAD

**Issue by SkillzGamingYT** [Nuytemans-Dieter/BetterSleeping#61]
I run the server where some of my players doesn't want to change the time to morning (killing off mobs, things that can only be done in the night) So, please add an option on the chat message or whatever to cancel the server time change (abort the sleep). Thanks.

**Comment by Nuytemans-Dieter** [comment]
Thank you for your suggestion, I will consider this. It's not easy to decide whether or not this would improve the plugin for most servers as the core idea of the plugin is to allow the night to be skipped more easily.
It will take a while but I will come back to you when I have made up my mind.

Once again, thank you for your suggestion!

**Comment by Nuytemans-Dieter** [comment]
I want to thank you again for your idea, definitely let me know if you have any other suggestions.
However, I will not implement this one for the following reason: I think it would be annoying for the people who went all the way to their bed to skip the night if it were suddenly cancelled by a single player. If you set the percentage high enough, the decision to skip the night would be in the benefit of most players. 

I hope to hear from you again in the future!

**Comment by SkillzGamingYT** [comment]
Hello, it @Nuytemans-Dieter, it might be a better idea to have an option for that in the config.
So server that are private (like HermitCraft) still be able to enable that option and big server network could disable that option

**Comment by Nuytemans-Dieter** [comment]
That's true, an extra options wouldn't hurt anyone. It might take a while though but I'll see what I can do!

**Comment by turikhay** [comment]
I'd also suggest adding "/dontskip" command (or something like that), so players would be able to temporarily set the percentage to 100 until the next morning.

**Comment by Nuytemans-Dieter** [comment]
> I'd also suggest adding "/dontskip" command (or something like that), so players would be able to temporarily set the percentage to 100 until the next morning.

That's a good idea, seems a bit more user friendy to me and might be a better alternative than clicking the chat. Consider it planned, but I'm going on holiday for a week so it might take a while.

Ps. I like the PSVR headset in your profile picture.
