### ISSUE TITLE
lang.yml file resseting

### ISSUE THREAD

**Issue by MpRtato** [Nuytemans-Dieter/BetterSleeping#62]
every time i edit the lang.yml files message texts, on server boot up it puts up an error and resets them to default.
--------------------------------------
the error message:

[10:35:54] [Server thread/INFO]: [BetterSleeping] 13 Missing options have been found in lang.yml!
[10:35:54] [Server thread/INFO]: [BetterSleeping] Please add the missing option(s) manually or delete this file and perform a reload (/bs reload)
[10:35:54] [Server thread/INFO]: [BetterSleeping] The default values will be used until then
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: prefix with default value: "&6[BetterSleeping] &3"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: enough_sleeping with default value: "Enough players are sleeping now, the night/storm will be skipped in <time> [second.seconds]!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: good_morning with default value: "Good morning! Have a great day, <receiver>!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: cancelled with default value: "<user> left their bed! Waiting for <amount> more [player.players] to sleep. <current_amount>/<total_amount>"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: amount_left with default value: "<user> is falling asleep. There [is.are] <amount> more [player.players] needed to skip the night/storm! <current_amount>/<total_amount>"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: sleep_spam with default value: "You have to wait <time> more [second.seconds] before you can sleep again!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: buff_received with default value: "You feel well rested and received <amount> [buff.buffs]!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: no_buff_received with default value: "You didn't sleep and feel tired, so you didn't receive [a.<amount>] [buff.buffs]!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: no_permission with default value: "&4You don't have permission to execute that command!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: message_reloaded with default value: "Reload complete!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: bypass_message with default value: "You have got bypass permissions so you don't need to sleep, <receiver>."
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: not_night_yet with default value: "&4You don't feel tired yet, <receiver>!"
[10:35:54] [Server thread/INFO]: [BetterSleeping] Missing option: not_all_players_bypassed with default value: "&4Not all players in your world have got bypass permissions!"

**Comment by Nuytemans-Dieter** [comment]
Thank you for contacting me! Could you send me your lang.yml? Then I'll be able to see what's wrong and help you. 

Thank you.

**Comment by MpRtato** [comment]
sorry for the late response, here:
------------------------------------------
# ################ #
#  BetterSleeping  #
# ################ #

# CONFIGURATION GUIDE:
# The symbol '&' is used for color codes
# Any message can be disabled by setting the text to "ignored" or "", an example can be found below
# some_setting: "ignored"
# another_setting: ""

# BetterSleeping offers support for several placeholders:
# <current_amount>
#     Replaced by:      The current amount of something.
#     Can be used in:   cancelled, amount_left
#     Example:          When 5 players are sleeping, it will be replaced by 5
# <amount>
#     Replaced by:      The correct number in that context.
#     Can be used in:   cancelled, amount_left, buff_received, no_buff_received
#     Example:          When 5 players are sleeping and 7 are required, it will be replaced by 2
#     Example:          When 3 buffs are enabled, it will be replaced by 3
# <total_amount>
#     Replaced by:      The correct total amount needed in that context, not considering the current amount
#     Can be used in:   cancelled, amount_left
#     Example:          When 7 sleeping players are required, it will be replaced by 7
# <time>
#     Replaced by:      The correct time (in seconds)
#     Can be used in:   enough_sleeping, sleep_spam
# <receiver>
#     Replaced by:      The player receiving the message
#     Can be used in:   Every message!
# <user>
#     Replaced by:      The player who did an action (enter or leave a bed for example)
#     Can be used in:   cancelled, amount_left

# Singular/plural nouns are taken in account too!
# Simply add [singular.plural] in an applicable message and it will be correctly substituted.
# The <amount> tag is always used as reference. This means that <current_amount> or <total_amount> are not considered in this process.
# Can be used in:   enough_sleeping, buff_received, no_buff_received, cancelled, amount_left, sleep_spam
# Example: <amount> more [player.players] [is.are] needed!
#          When 1 more player is needed, the singular sides will be taken: 1 more player is needed
#          Otherwise, the plural sides will be chosen: 5 more players are needed


# ---------------- #
# General messages |
# ---------------- #

# This is the text that will be put in front of all messages
# Feel free to change this prefix if you want to but I would be grateful if you kept the name of my plugin in the prefix
prefix: "&6[BetterSleeping] &3"


# The message people get when enough people are sleeping
enough_sleeping: "Enough players are sleeping, the night/storm will be skipped in <time> [second.seconds]!"


# The message people receive after the night/storm has been skipped
good_morning: "it morn"


# Players will receive this message if the skipping of the night is cancelled due to someone leaving their bed
cancelled: "<user> left their bed! Waiting for <amount> more [player.players] to sleep. <current_amount>/<total_amount>"


# This message indicates how many more people need to rest
# Will be sent to all online players (or all players in a specific world depending on multiworld_support)
# Sent when someone enters a bed
amount_left: "<user> is sleeping. There [is.are] <amount> more [player.players] needed to skip the night/storm! <current_amount>/<total_amount>"


# Players that try to enter their bed too quickly after getting out of it
sleep_spam: "You have to wait <time> more [second.seconds] before you can sleep again!"

# -------------- #
# Buffs messages |
# -------------- #

# Players that went to bed will get this message if buffs are enabled
buff_received: "You slep and receive <amount> [buff.buffs]! \o/"


# Players that didn't sleep will receive this message after the night was skipped if buffs are enabled
no_buff_received: "You didn't fall asleep, so you didn't receive [a.<amount>] [buff.buffs]!"


# ---------------- #
# Command messages |
# ---------------- #


# The message a player gets when they don't have access to a command and tries to execute it anyway
no_permission: "&4You don't have permission to execute that command!"


# The message that will be sent to the command sender and console when a BetterSleeping reload is complete
message_reloaded: "Reload complete!"


# --------------- #
# Bypass messages |
# --------------- #

# A bypass is given to players with permission bettersleeping.bypass OR essentials.sleepingignored
# And it is given to players with ignored gamemodes (this can be set in config.yml but is disabled by default)

# This message is sent when a player tries to sleep but they have got a bypass permission
# Permissions include bettersleeping.bypass and essentials.sleepingignored
bypass_message: "hmmmm, <receiver>."


# This message is sent when it isn't nighttime yet when performing /bs skip
not_night_yet: "&4it's not night/storm, <receiver>!"


# This message is sent when a user performs /bs skip and not all players in that world have bypass permissions
not_all_players_bypassed: "&4Not all players in your world have hmmmed!"

**Comment by Nuytemans-Dieter** [comment]
No problem! Thank you. I will take a good 
look tomorrow as I'm not home until then.

**Comment by MpRtato** [comment]
alright

**Comment by Nuytemans-Dieter** [comment]
Did you by any chance get an error like below (should be right above my red custom error)? 

> [11:57:02] [Server thread/ERROR]: Cannot load plugins\BetterSleeping\lang.yml
> org.bukkit.configuration.InvalidConfigurationException: expected '<document start>', but found '<block mapping start>'
>  in 'string', line 51, column 1:
>     prefix: "&6[BetterSleeping] &3"
>     ^
> 
>         at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at be.dezijwegel.files.ConfigAPI.<init>(ConfigAPI.java:54) [BetterSleeping.jar:?]
>         at be.dezijwegel.files.Lang.<init>(Lang.java:38) [BetterSleeping.jar:?]
>         at be.dezijwegel.management.Management.<init>(Management.java:33) [BetterSleeping.jar:?]
>         at be.dezijwegel.BetterSleeping.startPlugin(BetterSleeping.java:56) [BetterSleeping.jar:?]
>         at be.dezijwegel.BetterSleeping.onEnable(BetterSleeping.java:39) [BetterSleeping.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:776) [spigot.jar:git-Spigot-9de398a-8b09d98]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> Caused by: org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found '<block mapping start>'
>  in 'string', line 51, column 1:
>     prefix: "&6[BetterSleeping] &3"
>     ^
> 
>         at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:226) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:111) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot.jar:git-Spigot-9de398a-8b09d98]
>         ... 17 more

**Comment by MpRtato** [comment]
yeah

**Comment by MpRtato** [comment]
ffs im dumb, okey i found the issue it culdnt recognize the letter "o" or dashes.

**Comment by MpRtato** [comment]
but thanks for the help anyway

**Comment by Nuytemans-Dieter** [comment]
Haha that's alright, I think we've all been there at some point. You're welcome!
