### ISSUE TITLE
Change spawn location during daytime

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [Nuytemans-Dieter/BetterSleeping#76]
> Curious if it would be possible to allow beds to be entered during the day for players to move their spawn location instead of having to wait for the night or a storm.

Suggestion by user Borst on the Discord server.

**Comment by turikhay** [comment]
This will be [implemented in 1.15](https://www.minecraft.net/en-us/article/minecraft-snapshot-19w36a)
> Trying to sleep in a bed during daytime will now set the player’s spawn location to that bed

**Comment by Nuytemans-Dieter** [comment]
Thank you for pointing that out! I'll make sure BetterSleeping is compatible

**Comment by Nuytemans-Dieter** [comment]
This has been confirmed to still be working. Closing the issue.
