### ISSUE TITLE
New buff: Saturation

### ISSUE THREAD

**Issue by Adissaric** [Nuytemans-Dieter/BetterSleeping#96]
Just a personal request. I currently use regeneration but for my uses I think that Saturation would be far more useful.

**Comment by Nuytemans-Dieter** [comment]
Thank you for your suggestion. Luckily for you, a friendly user has [implemented](https://github.com/Nuytemans-Dieter/BetterSleeping/pull/95) this for us so in the next update, we'll have this as a new buff!
