### ISSUE TITLE
Accelerate instead of just skipping

### ISSUE THREAD

**Issue by rajmondx** [Nuytemans-Dieter/BetterSleeping#97]
Wrote this for a friend but you might use it as well (was too lazy to fork :P)

Changes from commit 8b07d8484bbf306bbe54dbddccc67b827aab52f5  

**Preview:** https://imgur.com/a/lGPK45D

**Diff:** https://pastebin.com/xRYK0bsX

**Comment by rajmondx** [comment]
Maybe you want to dynamically adapt `howOftenToExecutePerSecond` to let the stars move smoother => If you sleep at 22000 you gonna skip less time (looks smother) than if you sleep at 13000 which looks like the preview. 

And you should reconsider this part:

```
                  if (world.getTime() <= 500 && world.getTime() >= 0) {
                       return;
                   }

                   world.setTime(acceleratedTime);

                   world.setStorm(false);
                   sleepTracker.worldWasSetToDay(world);

                   if (BetterSleeping.debug) {
                       Bukkit.getLogger().info("-----");
                   }
```

because it could happen that the `setStorm` and `worldWasSetToDay` wont be called (code above was written dirty&fast).

**Comment by Nuytemans-Dieter** [comment]
Thank you for this suggestion and providing some code! Consider this planned for the future as an option (perhaps the old behavior will remain the default until I rewrite the whole plugin again). It won't fit in the next update (2.6.1) but I'm aiming to get this into the one after that.

Cheers!

**Comment by Nuytemans-Dieter** [comment]
This is now possible in the early 3.0.0 dev version
